corrected_gpio_config_builder
IAmMarcelJung/fabulous-board-example pull request #15
Opened 2024-06-10 09:15 UTC by Biswajitks1

Issue:
The GPIO configuration builder did not correctly handle the initial case, causing the configuration for pin[1] to fail. This resulted in incorrect SPI interface settings.
Fix:
The code has been updated to ensure that the configuration of pin[0] fails gracefully while correctly configuring pin[1]. This adjustment ensures that the SPI interface is now properly configured.
Impact:
With this fix, the FPGA can be reflashed without needing to power it off.

2024-06-13 15:29 UTC, IAmMarcelJung requested changes
Please implement the suggestions.

2024-06-13 15:29 UTC, IAmMarcelJung commented on gpio_test/build_custom_firmware/Makefile
> +	sudo python3 ../util/caravel_hkflash.py  $<
Please remove this, this might only be related to your local setup

2024-06-13 15:29 UTC, IAmMarcelJung commented on gpio_test/gpio_config/gpio_config_builder.py
> +dum=1
What is this used for? It should be removed.

2024-06-13 15:29 UTC, IAmMarcelJung commented on gpio_test/gpio_config/gpio_config_builder.py
> +                   # 1100000000001
Why is this commented out?

2024-06-13 15:29 UTC, IAmMarcelJung commented on gpio_test/gpio_config/gpio_config_builder.py
> +        s = stream + "0000000000000"
Please remove trailing whitespaces.

2024-06-13 15:29 UTC, IAmMarcelJung commented on gpio_test/gpio_config/gpio_config_builder.py
> +print("hefiw````````````````````ugfiwgfiubgifrb")
Remove these lines.

2024-06-13 15:29 UTC, IAmMarcelJung commented on gpio_test/gpio_config/gpio_config_builder.py
> +
Please format using black formatter.

2024-06-13 15:29 UTC, IAmMarcelJung commented on gpio_test/gpio_config/gpio_config_builder.py
> +    elif gpio_l[k][1] == H_NONE: #generalise this may be by using NUM_IO and knowing which pin is faulty and just hard coding that pin's stream based on the violation type
"Hardcoding" is fine here since this applies only to the H_NONE pins. The comment can therefore be removed.

2024-06-13 15:29 UTC, IAmMarcelJung commented on gpio_test/gpio_config/gpio_config_builder.py
> +        #stream_l = build_stream_none(stream_l, config_l[k]+2)
Please remove the commented out lines.

2024-07-04 20:23 UTC, Biswajitks1 commented
sorry for the late.I did the changes accordingly.Thank you.
Please let me know if any changes are required.

2024-07-04 22:04 UTC, IAmMarcelJung approved these changes
Thanks, this looks all good!

2024-07-04 22:06 UTC, merged